name: Node.js CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn install
    - run: yarn test
      env:
        CI: true
    - uses: actions/upload-artifact@v1
      with:
        name: screenshot-example-com
        path: screenshot.png